// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrwM5h8Xo4kcq9dPekYWP1_zdf_yv4cdo',
    appId: '1:727948714656:web:fd05aabb3f7ff51c569fc5',
    messagingSenderId: '727948714656',
    projectId: 'samets-ice-cream-shop',
    authDomain: 'samets-ice-cream-shop.firebaseapp.com',
    storageBucket: 'samets-ice-cream-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfc4g4McfDDyZYkgYJI98sxdT4RdSQMI',
    appId: '1:727948714656:android:bca24439a281b9fb569fc5',
    messagingSenderId: '727948714656',
    projectId: 'samets-ice-cream-shop',
    storageBucket: 'samets-ice-cream-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMPPKwVEG0tHKv49i7QMq4DwIuejWPv4',
    appId: '1:727948714656:ios:7263748025d0daa5569fc5',
    messagingSenderId: '727948714656',
    projectId: 'samets-ice-cream-shop',
    storageBucket: 'samets-ice-cream-shop.appspot.com',
    iosClientId: '727948714656-15ean3ojc5psfpp9e54u42di02iokl4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.icecreamshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMPPKwVEG0tHKv49i7QMq4DwIuejWPv4',
    appId: '1:727948714656:ios:7263748025d0daa5569fc5',
    messagingSenderId: '727948714656',
    projectId: 'samets-ice-cream-shop',
    storageBucket: 'samets-ice-cream-shop.appspot.com',
    iosClientId: '727948714656-15ean3ojc5psfpp9e54u42di02iokl4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.icecreamshop',
  );
}
